### ISSUE TITLE
`ValueError:  Character [-] in not allowed in identifier` (for existing users)

### ISSUE THREAD

**Issue by Github-dm-CDE** [littleK0i/SnowDDL#121]
**Describe the bug**
I tried SnowDDL today and it looks very promising. 😊 
However, I have a problem with existing users on our Snwoflake account.
The Snowflake users in our company are synchronised to Snowflake via Azure Entra ID and AAD groups.
These users then have the following form for their `login_name`, for example: `ADMIN-D0123456`.

With a `snowddl plan`, SnowDDL apparently cannot find these users and does not even list them in the plan. When I try to add the users manually via a `user.yaml` file, for example to assign roles to them, I get the following error:
```bash
ValueError: Character [-] in not allowed in identifier [ADMIN-D0123456], only ASCII letters, digits and single underscores are accepted
```

**Expected behavior**
SnowDDL should correctly recognise the existing USers so that they can be used for further role assignments by SnowDDL.

**Attach log**
```bash
$ snowddl -c config/ -a ${ACCOUNT} -r ACCOUNTADMIN -u ${SNOWFLAKE_USER} -k ${PRIVAT_KEY_FILE} --passphrase ${PRIVAT_KEY_PASSWORD} -w XS --show-sql plan
2024-09-13 14:51:13.243 - WARNING - [/builds/customer-data-empowerment/sandbox/test-repos/snowddl-playground/config/user.yaml]: Traceback (most recent call last):
  File "/builds/customer-data-empowerment/sandbox/test-repos/snowddl-playground/venv/lib[64](https://gitlab.dm-drogeriemarkt.com/customer-data-empowerment/sandbox/test-repos/snowddl-playground/-/jobs/42460443#L64)/python3.9/site-packages/snowddl/parser/abc_parser.py", line 38, in parse_single_file
    return callback(file)
  File "/builds/customer-data-empowerment/sandbox/test-repos/snowddl-playground/venv/lib64/python3.9/site-packages/snowddl/parser/user.py", line 84, in process_user
    full_user_name = AccountObjectIdent(self.env_prefix, user_name)
  File "/builds/customer-data-empowerment/sandbox/test-repos/snowddl-playground/venv/lib64/python3.9/site-packages/snowddl/blueprint/ident.py", line 94, in __init__
    self.name = self._validate_part(name)
  File "/builds/customer-data-empowerment/sandbox/test-repos/snowddl-playground/venv/lib64/python3.9/site-packages/snowddl/blueprint/ident.py", line 47, in _validate_part
    raise ValueError(
ValueError: Character [-] in not allowed in identifier [ADMIN-D0123456], only ASCII letters, digits and single underscores are accepted
Cleaning up project directory and file based variables
```

**Attach YAML config (if applicable)**
users.yaml
```yaml
ADMIN-D0123456:
  login_name: ADMIN-D0123456
  display_name: Some, Name- Admin-D0123456
  email: Some.Name@email.de
  default_warehouse: XSMALL
  comment: AAD provisioned account
```

**Comment by littleK0i** [comment]
Ok, you have two options here.

**(1) Connect to Azure in Python, get info about users and create blueprints dynamically in the code**
Here is the documentation page: https://docs.snowddl.com/advanced/programmatic-config

Here is the structure of UserBlueprint: https://github.com/littleK0i/SnowDDL/blob/master/snowddl/blueprint/blueprint.py#L385-L399

Basically, instead of YAML config you may generate a small part of config dynamically.

This is the best option, since you will have full control over user object generation. You will be able to tweak any settings and adjust any names. Including replacement of hyphens with underscores.

**(2) Let Azure manage users and SnowDDL manage everything else**
Create SnowDDL config up to business roles, but do not create users. Let Azure create users and own them.

Azure probably can assign roles to newly created users. Point it to business roles created by SnowDDL.

This comes with a lot of limitations. You won't have full control over every parameter of user. You will be able to assign only one business role per users, since user roles do not exist. But things should work, more or less.

---

SnowDDL does not touch objects which are "owned" by other tools. That's why it does not touch users currently created by Azure.

Login name should accept any string. But user name is an identifier and is subject to strict naming policy introduced in SnowDDL. It helps to prevent account becoming a mess over time, and it helps to keep identifiers useable without double-quotes in most cases. Hyphen `-` is restricted on purpose.

**Comment by CM000n** [comment]
Just for the sake of interest: How does SnowDDL identify entities that "belong" to other tools? Entities (schemas, tables, etc.) that have been created by other users within snowflake, for example, are also recognized by SnowDDL and dropped or changed if necessary.

**Comment by littleK0i** [comment]
@CM000n , it uses "ownership" concept.

Each object in Snowflake is "owned" by some role. All account-level objects owned by SnowDDL role are managed by SnowDDL. All other account-level objects are ignored.

Schema-level objects in databases created by SnowDDL are managed by SnowDDL regardless of ownership. The idea is that databases created by SnowDDL should be fully managed by SnowDDL.

Also, you may set parameter `is_sandbox: true` for schemas. Other application (e.g. DBT) can create objects in these schemas, and objects won't be dropped if not listed in SnowDDL config.
