### ISSUE TITLE
Add support for TYPE property on users

### ISSUE THREAD

**Issue by apd-bbaker** [littleK0i/SnowDDL#128]
**Describe the solution you'd like**
Snowflake [has added a new TYPE property]([Optional object properties (objectProperties)](https://docs.snowflake.com/en/sql-reference/sql/create-user?mkt_tok=MjUyLVJGTy0yMjcAAAGWByE-0qEVBG_W0C211gttZZbxuEnyPEmxib8FKircedoQW2Qb5Fe3twuoI4x_fOovxPEEG3o_XKP9b0wgKM48u8_kfgJ0BSnHpZjtwFwDbQtGbfPxhg#optional-object-properties-objectproperties)) for users to accommodate person/service/legacy_service. This allows greater configurability of service accounts over the standard person user.

**Describe alternatives you've considered**
Currently using the default "person" type for all accounts in SnowDDL and it works well, but would be helpful as more of an infra focused tool to include this ability to define services. This is especially relevant when users are defined by an IdP and only service accounts exist as Snowflake logins.

**Additional context**
Interested in contributing to the codebase to add this functionality, but don't currently have the bandwidth to prioritize it.

**Comment by littleK0i** [comment]
This feature is a bit underwhelming tbh. Specifically this behaviour may cause a lot of problems:

> If a user has their TYPE property set to SERVICE using the ALTER USER command, then the incompatible properties remain stored, but are not returned in user views returned by commands such as DESCRIBE USER. The incompatible properties cannot be set using the ALTER USER command.

I'll try to add it and see how it works with edge cases. If this "magic" starts to conflict with declarative approach, we may recommend against using `TYPE`. But let's see how it goes.

On the bright side.. if you use SnowDDL to manage users, their properties should be in perfect shape by design. Some arbitrary rules around `TYPE` barely add any value.

**Comment by MaRo99382** [comment]
We have the need for the TYPE property as well.
@littleK0i you say you might recommend against it. But what is the alternative to using the TYPE property and thus having it availabe in SnowDDL?
I might/probably have gotten this wrong, but my current understanding is:
The new built-in authentication policy for new Snowflake accounts (and in the future also existing accounts) of BCR bundle 2024_08 means that all current users we have set up with SnowDDL, which have the TYPE=NULL (->which means TYPE=PERSON), will have MFA enabled. Since we are using SnowDDl for Service Users, those users would not be usable under MFA anymore.
I see as an alternative,the option of creating a custom authentication policy that disables this somehow, but we would not be able to manag that via SnowDDL then.

**Comment by littleK0i** [comment]
Yeah, I saw this email.

No worries, I'll add `TYPE` for User, auth policies and session policies in the next update.

**Comment by littleK0i** [comment]
@apd-bbaker , `type` is available in version `0.33.0`.

Please note, if you have any parameters conflicting with `SERVICE` or `LEGACY_SERVICE` type, SnowDDL will raise ValueError. These parameters must be removed in order to prevent unwanted "magic" implemented by Snowflake along with user types.

**Comment by apd-bbaker** [comment]
> @apd-bbaker , `type` is available in version `0.33.0`.
> 
> Please note, if you have any parameters conflicting with `SERVICE` or `LEGACY_SERVICE` type, SnowDDL will raise ValueError. These parameters must be removed in order to prevent unwanted "magic" implemented by Snowflake along with user types.

Thanks! Will test this one out also. We're managing only service accounts at the moment and deprecating Snowflake native logins in favor of IdP. That's a whole other complexity I'm working through at the moment with regard to assigning __u_roles to IdP created users.

**Comment by apd-bbaker** [comment]
@littleK0i Confirmed this is looking good on service, legacy_service, and person types.

**Comment by littleK0i** [comment]
You may fetch users from IdP and generate `UserBlueprints` with [programmatic config](https://docs.snowddl.com/advanced/programmatic-config).

It will help you to keep full control over all user parameters. IdP is too limited in Snowflake, creates more problems than solutions.

**Comment by littleK0i** [comment]
@apd-bbaker , JFYI, authentication policies are available from `0.34.0`: https://docs.snowddl.com/basic/yaml-configs/authentication-policy

**Comment by MaRo99382** [comment]
@littleK0i thank you very much!
Unrelated question, that came up when seing your releases:
Is there a particular reason, why the package is in a 0 major version release still?
Or do you simply not follow semantic versioning and did not bother pushing the major version at some point?

**Comment by littleK0i** [comment]
@MaRo99382 , I would bump major version to 1 when when lib gets to the next level of adoption and scope. For example:

- It becomes "officially recommended" by vendor and moves to the main org. It happend with [pyexasol](https://github.com/exasol/pyexasol) in the past.
- It becomes part of consistently paid product or consulting service. This would increase requirements for backwards compatibility and testing.
- Velocity of changes and number of maintainers goes up sufficiently.
