### ISSUE TITLE
Adding Cortex permission to the business roles

### ISSUE THREAD

**Issue by marystory** [littleK0i/SnowDDL#158]
**Is your feature request related to a problem? Please describe.**

I would like to be able to grant permission to create `CORTEX SEARCH SERVICE`

`create or replace CORTEX SEARCH SERVICE CC_SEARCH_SERVICE_CS`

**Describe the solution you'd like**

Please add `CORTEX_SEARCH_SERVICE` to the list of supported business roles. Thanks

**Comment by littleK0i** [comment]
Is it good enough if `CORTEX SEARCH SERVICE` becomes available in permission model settings `owner_create_grants`, `owner_future_grants`?
https://docs.snowddl.com/basic/yaml-configs/permission-model

There is no point granting it to business role, since search service is a schema object and belongs to schema owner role. But schema owner role can be granted to business role, and such business role will be able to create search services.

Not sure if it makes sense to implement this object type in SnowDDL natively. It seems to be fully refreshed on creation, so it is not a truly DDL statement anymore. Probably does not work well with automated testing and env prefix.

**Comment by marystory** [comment]
Adding it to the permission model works as well. Thank you

**Comment by littleK0i** [comment]
@marystory , added object type `CORTEX_SEARCH_SERVCE` in `0.36.2`.

How to use.

1. Create permission model:
```yaml
default_with_cortex:
  inherit_from: default

  owner_create_grants:
    - CORTEX_SEARCH_SERVCE

  owner_future_grants:
    CORTEX_SEARCH_SERVCE: [OWNERSHIP]
```

2. Use permission model for schema
```yaml
permission_model: default_with_cortex
```

3. Grant schema owner to business role which should be able to create cortex searches in this schema:
```yaml
my_fancy_role:
  schema_owner: my_fancy_schema
```

**Comment by littleK0i** [comment]
(Closing this issue for now, should be resolved)
