### ISSUE TITLE
Issues with special characters in imported tables/views

### ISSUE THREAD

**Issue by abrostoff** [littleK0i/SnowDDL#43]
**Issue description:**
SnowDDL is encountering errors due to special characters in database tables in a Snowflake marketplace database, causing inconvenience. Attempts to resolve the issue using workarounds have been unsuccessful.

**Expected behavior:**
 SnowDDL should be able to handle special characters in database tables without causing errors or deleting the user’s privilege for the shared database.

**Error log:**
raise ValueError(f"Character [{char}] in not allowed in identifier [{val}], only ASCII letters, digits and single underscores are accepted")
ValueError: Character [-] in not allowed in identifier [aact_eaa04-20160303], only ASCII letters, digits and single underscores are accepted

If you want to reproduce the error, you can try using the snowflake marketplace dataset I am using - it's called `economy_data_atlas` by Knoema

**Comment by littleK0i** [comment]
I've checked the marketplace dataset and I see view called `aact_eaa04-20160303`. Nasty naming, but in theory it should not affect SnowDDL, since this view comes from an inbound SHARE.

Such SHARE should not be "owned" or managed by SnowDDL admin role. It should be owned by some other role (e.g. `ACCOUNTADMIN`), and you would normally create an another reader role with `GRANT IMPORTED PRIVILEGES` on SHARE. This reader role can be granted to SnowDDL [business roles](https://docs.snowddl.com/basic/yaml-configs/business-role) using `global_roles` config parameter.

Full setup:

```sql
-- Inbound share, owned by ACCOUNTADMIN
CREATE DATABASE "ECONOMY_DATA_ATLAS" FROM SHARE ...;

-- Role with read access to inbound share
CREATE ROLE "ECONOMY_DATA_ATLAS_READ_ROLE";
GRANT IMPORTED PRIVILEGES ON DATABASE "ECONOMY_DATA_ATLAS" TO ROLE "ECONOMY_DATA_ATLAS_READ_ROLE";

-- Make role available for super-admin and SnowDDL-admin
GRANT ROLE "ECONOMY_DATA_ATLAS_READ_ROLE" TO ROLE "ACCOUNTADMIN";
GRANT ROLE "ECONOMY_DATA_ATLAS_READ_ROLE" TO ROLE "SNOWDDL_ADMIN_ROLE";
```

**business_role.yaml**
```yaml
analyst:
  schema_read:
    ...
  warehouse_usage:
    ...
  global_roles:
    - economy_data_atlas_read_role
```

With this setup SnowDDL should never access individual objects in shares and should never encounter "invalid" identifiers.

---

If you tried to do something else, please share a sample of YAML config and a full exception stack. I'll take a look.

Thank you!
