### ISSUE TITLE
Directory of Outbound Shares

### ISSUE THREAD

**Issue by richard-cybersyn** [littleK0i/SnowDDL#45]
**Is your feature request related to a problem? Please describe.**
We as an organization will have a lot of outbound shares, so having a directory to place them in would be helpful for better organization, over 1 file.

**Describe the solution you'd like**
Directory of outbound shares.
```
outbound_shares
│   share_one.yaml
│   share_two.yaml
```

**Describe alternatives you've considered**
Writing all of the shares in the `outbound_share.yaml`

**Additional context**

**Comment by littleK0i** [comment]
In theory, this type of config should be available for all types of account objects: users, roles, warehouses, etc.

However, all directories are currently reserved for databases and schemas. For example, if someone wants to create a database with name `outbound_share` or `user`, this person should be able to do so.

We may use special character prefix for directory names, like `%outbound_shares`, but it might complicate things even further. That's why I am still on the fence about this specific feature.

**Comment by richard-cybersyn** [comment]
I agree the tradeoffs around how to manage something like this might be difficult. Based on how the overall structure exists today, you wanted to have account objects at the root level, with all other objects located in directories to best represent how the object structure exists in Snowflake?
