### ISSUE TITLE
Further Separation of Environments when using env-prefix

### ISSUE THREAD

**Issue by abrostoff** [littleK0i/SnowDDL#52]
Is your feature request related to a problem? Please describe.
We are using schemachange with the --env-prefix parameter. Because separation of environments is very important to us, it is vital that each environment has its own user with its own password that does not have access to other environments. When using the env-prefix, it creates a snowddl_admin role corresponding to the given prefix ({{env-prefix}}__snowddl_admin role ), which seems like it would be a good solution for separating environments, the only problem is that it grants this {{env-prefix}}__snowddl_admin role usage on snowddl_admin role (regular). This means that {{env-prefix}}__snowddl_admin has access to edit and drop tables in all environments. 

Describe the solution you'd like
schemachange creates a new user for each environment. This user will only have access to objects related to its environment, and does not have the ability to edit snowflake objects in other environments.

**Comment by littleK0i** [comment]
It should be other way around, based on this line of code: https://github.com/littleK0i/SnowDDL/blob/master/snowddl/context.py#L76

`SNOWDDL_ADMIN` role and all its privileges are granted to `{{ENV_PREFIX}}__SNOWDDL_ADMIN` role. In theory, prefixed admin roles should not be able to see objects created by other prefixed admin roles. But they might still see it due to inherited `SYSADMIN` and `SECURITYADMIN` roles.

The main problem with creating a brand new role is related to extra permissions which might be granted to `SNOWDDL_ADMIN` role. For example:

- Warehouse: https://docs.snowddl.com/guides/other/admin#administration-warehouse
- Inbound shares: https://docs.snowddl.com/guides/other/admin#shares
- Integrations: https://docs.snowddl.com/guides/other/integrations
- Global roles: https://docs.snowddl.com/guides/role-hierarchy

These objects are managed outside of SnowDDL and are normally owned by `ACCOUNTADMIN` role. I suspect SnowDDL will not be able to copy custom privileges to objects it does not manage.

Also, ENV prefix is generally meant to be a feature for development. If you want to create separate sub-environments in production, it might be worth using separate Snowflake accounts instead. And most likely you'll have at least some differences. Like different user names, slightly different roles, etc.

I think it is a bit unusual to have perfect carbon copies on multiple environments on prod.

Please feel free to provide more details about your specific use case. We'll try to figure it out.

**Comment by abrostoff** [comment]
Currently, we are trying to avoid opening a new snowflake account, and we were wondering if we could have three environments:

* Feature branch (prefix foo)
* Development (prefix dev)
* Production (no prefix) 

Do you think we can achieve something like that without opening a dedicated snowflake account for production. We would need to be assured that there is no way for feature or dev prefixed roles can create/drop snowflake objects in production. 

Currently, we ran snowddl (using snowddl admin) with the env prefix dev. Here is exactly what we ran:

```
  snowddl \
  -c snowddl-admin \
  -a $SNOWFLAKE_ACCOUNT \
  -u $SNOWFLAKE_USERNAME \
  -p $SNOWFLAKE_PASSWORD \
  --env-prefix $ENV_PREFIX \
  --show-sql \
  apply
```

 After that, we ran some queries to see what access the dev_snowddl_admin role had, and if it was able to drop a schema that was created by snowddl admin (with no prefix). Here are the queries:

```
use role DEV__SNOWDDL_ADMIN;
drop schema dashboard.data_science;
``` 

The schema dashboard.data_science was successfully dropped, which is extremely problematic for us.

**Comment by littleK0i** [comment]
I see. If you want to keep the current setup with one account, I suggest to create two separate SnowDDL admin users with two different roles:

- one user for PROD environment (without prefix);
- another user for DEV environment (everything with prefix);

With this approach DEV and PROD will not mix-up, and prefixed admin users will not have any extra access.

---

However, I strongly suggest to use separate Snowflake account and separate S3 / GCP buckets for PROD environment. It will be especially important when number of objects and complexity increases in a few months or years.
