### ISSUE TITLE
Grant Create Dynamic Table Privileges to Schema Owner

### ISSUE THREAD

**Issue by chris-leigh-dignifi** [littleK0i/SnowDDL#54]
**Is your feature request related to a problem? Please describe.**
Currently, the schema owner role is not granted the privileges to create, monitor or operate on dynamic tables.

**Describe the solution you'd like**
Schema owner role should automatically be given permission to create dynamic tables within schema.

**Describe alternatives you've considered**
The workaround I am going to proceed with is managing these permissions via tech role.

**Comment by littleK0i** [comment]
Thank you for raising up this question.

`CREATE DYNAMIC TABLES` and a few more similar grants (like `CREATE MATERIALIZED VIEW`) are not included with `OWNER` role by default due to potential to incur massive costs.

For example, there would be nothing to stop the "owner" of schema from creating a few thousand dynamic tables running in the background every minute. It may even bypass and surprise standard monitoring systems, since the "dynamic table" feature is very new.

Using a "tech role" to add this privilege for only a few dedicated technical users is a good idea.

Also, as far as I know, currently there are no "future grants" for dynamic tables. But standard `GRANT SELECT ON FUTURE TABLES IN SCHEMA ...` works with dynamic tables somehow. So users with `READ` role should be able to access data in dynamic tables without any extra permissions.

---

I may consider adding the possibility to specify extra grants in `params.yaml` for schema roles, if this request becomes popular.
