### ISSUE TITLE
UDTF python functions do not appear to be supported

### ISSUE THREAD

**Issue by oz-chewie** [littleK0i/SnowDDL#63]
**Describe the bug**
SnowDDL has UDF python support, but no UDTF support.  The returns attribute in yaml does not appear to work with a TABLE() definition of fields that the python class can return.

**Expected behavior**
Full UDTF python support

**Attach log**
```
ValueError: Could not parse data type string [TABLE ("SN" VARCHAR(64))]
```

**Attach YAML config (if applicable)**
```
language: PYTHON
runtime_version: "3.10"
arguments:
  states: VARCHAR(255)

returns: TABLE ("SN" VARCHAR(64))

handler: CycleSummarizer

body: |-
    import logging
    import json
    import time
    import datetime

    logger = logging.getLogger("python_logger")

    class DgoSummarizer:
        def __init__(self):
            self._count = 0

        def process(self, states: str):
            statearray = json.loads(states)
[...]
```

**Comment by littleK0i** [comment]
`RETURNS TABLE (...)` is supported, but uses slightly different syntax (dict to specify columns instead of string):

```
arguments:
  states: VARCHAR(255)

returns:
  sn: VARCHAR(64)
```

Here is a working example:
https://github.com/littleK0i/SnowDDL/blob/master/test/_config/step1/db1/sc1/function/fn004_fn1(varchar%2Cnumber%2Cnumber).yaml#L9-L11

Docs page (please note the `- OR -` part): https://docs.snowddl.com/basic/yaml-configs/function

Thank you.

**Comment by oz-chewie** [comment]
Excellent - totally works.  Thanks for the prompt response!
