### ISSUE TITLE
Grant Usage of Single Object Created/Managed Outside of SnowDDl

### ISSUE THREAD

**Issue by christopher-leigh** [littleK0i/SnowDDL#84]
**Is your feature request related to a problem? Please describe.**
I would love some guidance on the following use case:

I want to grant a user access to a single table, but this table is created and managed outside of SnowDDL via our Dbt CI/CD. For all of our tables that are managed by dbt, we are utilizing the `is_sandbox` parameter so SnowDDL doesn't destroy any of our objects created through dbt. However, I am now finding that I can only manage permissions at the schema-level, rather than at the table/view level. Any recommendations on how I can grant a user access to this single table within our schema? I've tried utilizing a tech role (i believe this is how it should be managed), but receiving this error:

```
 File "/opt/homebrew/lib/python3.9/site-packages/snowddl/parser/abc_parser.py", line 28, in parse_single_file
    return callback(file)
  File "/opt/homebrew/lib/python3.9/site-packages/snowddl/parser/tech_role.py", line 50, in process_tech_role
    raise ValueError(f"No {ObjectType[on].plural} matched wildcard grant with pattern [{pattern}]")
ValueError: No TABLES matched wildcard grant with pattern [mart.legacy.table_name]
```

Example of my `tech_role.yaml`:

```
restricted_mart_legacy:
  grants:
    DATABASE:USAGE:
      - mart
    SCHEMA:USAGE:
      - mart.legacy
    TABLE:SELECT:
      - "mart.legacy.table_name"
```

Example of the `param.yaml` of the `legacy` schema of the `mart` database:

```
comment: Schema for legacy logic
is_sandbox: true
```

**Describe the solution you'd like**
I'd like to be able to manage the access of lower-level object (table, view) that is created and managed outside of SnowDDL. 

**Describe alternatives you've considered**
Developing a tool that automatically loads our dbt object metadata into SnowDDL configs.

**Additional context**
Add any other context or screenshots about the feature request here. Also, links to relevant pages of Snowflake documentation.

**Comment by littleK0i** [comment]
As far as I know, it is one of many fundamental issues with dbt: re-creation of tables on every run.

The only way to define privileges on specific objects in SnowDDL is to manage these objects in SnowDDL. Otherwise these objects may not exist, so no grants can be processed.

You may try to add YAML config for this table and see if it is possible to avoid `CREATE OR REPLACE TABLE` in dbt somehow. Maybe you can switch dbt adapter to `INSERT OVERWRITE` or `TRUNCATE + INSERT` commands.

In the worst case scenario you may run basic SQL script with specific `INSERT OVERWRITE` command instead.

**Comment by littleK0i** [comment]
On a second thought... You should be able to use explicit `GRANT...` in post-hook.

It should work, but with a few caveats:

1. Dbt user may require additional permissions to manage grants.
2. You may experience access errors sometimes due to race condition.

There is a short delay between `CREATE OR REPLACE TABLE` and `GRANT` statements. Object will not be accessible in this brief moment.

As far as I know, the only way to provide grants in Snowflake without race conditions is it use future grants.

**Comment by christopher-leigh** [comment]
Thanks @littleK0i for the very thoughtful responses! This has been helpful for me to think through this. I'm going to attempt something similar to your second suggestion, where I am going to manage access to specific dbt generated objects through dbt's [grants config](https://docs.getdbt.com/reference/resource-configs/grants#:~:text=You%20can%20use%20the%20grants,have%20configured%20on%20the%20resource.).

I'm working on testing it out now and will let you know how this solution works.

**Comment by christopher-leigh** [comment]
Alrighty, my solution is as follows: 

1) Gave my dbt user permission to manage grants: 
```sql
grant manage grants ON ACCOUNT to <env>__dbt__u_role;
```
2) Created a restricted tech_role that give the role USAGE access to database and schema
```yaml
restricted_mart_legacy:
  grants:
    DATABASE:USAGE:
      - mart
    SCHEMA:USAGE:
      - mart.legacy

  comment: "Usage access to mart.legacy schema"
```
3) Update the business role
```yaml
test:
  schema_read:
    - lake.schema
  warehouse_usage:
    - test
  tech_roles:
    - restricted_mart_legacy
```
4) Added grants config to `models.yaml`:
```yaml
  - name: dbt_model_name
    config:
      database: database
      schema: schema
      grants:
        select: ["{{target.name}}__test__u_role"]
```

**Comment by littleK0i** [comment]
Granting stuff directly to user role may not work. I suspect SnowDDL will notice extra grant and will try to drop it.

Alternative version:

1. Create a global role manually outside of SnowDDL. Grant `MANAGE GRANTS` to it.
2. Grant global role to business role of DBT user via `global_roles`.
3. In DBT grant access on model to global role as well.

The full chain is:
```
model table or view -> global role -> business role -> user role -> user
```

SnowDDL will not touch global roles and won't drop extra grants from these.
